### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by MitchellMeekins** [ZeroSharp/Chess.com_Analysis_Chrome_extension#12]
The extension no longer works for me on any website. For both chess.com/live and chess.com/play, the extension simply brings up the import screen on Lichess and does not enter the PGN. On every other site, the extension does not produce any result. This is Version 4.0.0.

**Comment by MitchellMeekins** [comment]
Occasionally, both chess.com/live and chess.com/play tries to download the PGN to my computer rather than export to Lichess. Either it tries to download the PGN to my computer or opens the import screen and fails to upload the PGN.

**Comment by johtso** [comment]
I'm not able to reproduce this..

**Comment by shamp00** [comment]
Looks like chess.com have changed something to do with the download button. I'll submit a fix to the Chrome extensions team asap.

**Comment by shamp00** [comment]
Version 4.0.1 is now available.
