### ISSUE TITLE
Imports not working

### ISSUE THREAD

**Issue by gyrex** [ZeroSharp/Chess.com_Analysis_Chrome_extension#13]
Hi, the extension doesn't appear to be working at the moment unfortunately.

After attempting to import, this is the resulting PGN in lichess:

[Event "Live Chess"]
[Site "https://lichess.org/FP4Cbd5w"]
[Date "2022.04.17"]
[White "?"]
[Black "?"]
[Result "*"]
[UTCDate "2022.04.17"]
[UTCTime "02:37:22"]
[WhiteElo "?"]
[BlackElo "?"]
[Variant "Standard"]
[TimeControl "-"]
[ECO "?"]
[Opening "?"]
[Termination "Unterminated"]
[Annotator "lichess.org"]

*

**Comment by shamp00** [comment]
Thanks for letting me know. A fixed extension has been submitted to the Chrome extensions team. Should go live in a couple of days. Look out for version 4.0.2.

**Comment by gyrex** [comment]
Thanks Robert. It's actually working now in 4.0.1. I think it may have actually been an error on cheess.com's side with some erroneous formatting of their PGN? 

Edit: Thanks also for a wonderful tool, I really appreciate it mate.

**Comment by shamp00** [comment]
Good to know it's working again. I think chess.com does canary testing with upcoming changes so it may break again soon. I'm not playing much chess right now so let me know.
