### ISSUE TITLE
Tutorial/demo

### ISSUE THREAD

**Issue by arthur-parmentier** [ZeroSharp/Chess.com_Analysis_Chrome_extension#3]
After installation, I could not figure out how it is supposed to work. Please provide a few steps or a little video demo to show what to so on the chess.com live page and on lichess.org.

**Comment by shamp00** [comment]
Hi Arthur,

Chess.com updated their website a few days ago and the current version
doesn’t work. There will be a fix in the next few days. I’ll try to submit
the fix tomorrow, but Chrome admins have to approve it which takes a few
days usually.

Using it is pretty obvious. When you have finished a game, either from the
archives, or at the end of your game, you click on the little yellow knight
and it opens a tab with the analysis from lichess.

Rob

**Comment by arthur-parmentier** [comment]
Thanks! With your recent fixes, I now got it working!
