### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by arthur-parmentier** [ZeroSharp/Chess.com_Analysis_Chrome_extension#4]
Hey, the extension stopped working again.
Here is what I get in the console:
VM196:9 Uncaught (in promise) TypeError: Cannot read property 'message' of undefined
    at <anonymous>:9:24

**Comment by shamp00** [comment]
Is this version 3.5.0? Where are you using it from? It works for me from both the game archives and the end of a live game.

**Comment by arthur-parmentier** [comment]
Yes it is v3.5.0. Actually, it has been working again since I wrote this issue, so I could not repeat it; it just happened once...
