### ISSUE TITLE
Doesn't trigger from live chess after completion of game.

### ISSUE THREAD

**Issue by abhigyank** [ZeroSharp/Chess.com_Analysis_Chrome_extension#5]
The extension doesn't trigger if clicked after completing a game at chesscom, from a url like https://www.chess.com/game/live/123456 . There are no logs in the console after clicking the extension.

**Comment by shamp00** [comment]
I can't replicate this in version 3.5.0. If I navigate to https://www.chess.com/game/live/123456 it forwards me to https://www.chess.com/live/game/123456 which seems to work ok. You need to be logged in to both chess.com and lichess.org. Can you check whether it's still a problem for you?

**Comment by abhigyank** [comment]
Sorry, I was probably not quite clear with the reproducing steps.
Steps: 
Start a game on chesscom and complete it. Url is of type: https://www.chess.com/game/live/123456 . After game is completed, try clicking the extension, it doesn't trigger, There are no logs as well, which I think suggests that the extension isn't being triggered.

My probable guess for this is that because the url is initially https://www.chess.com/play/online or https://www.chess.com/play/ and then changes something to like https://www.chess.com/game/live/123456 it doesn't trigger.

**Comment by shamp00** [comment]
Hmm I still have no problem after completing a game. 
Do you have some option set that I don't? My settings are as follows:

![Capture](https://user-images.githubusercontent.com/1511180/105066551-d3252600-5a76-11eb-85f6-b9a90d6f0990.PNG)

Are your settings any different?
Is it possible some other extension is interfering?
Are you maybe signed up for the chess.com beta? (I'm not.)

**Comment by shamp00** [comment]
Fixed by #7.
